datagrid:
  issues-grid:
    extended_entity_name: Vitalii\Bundle\TrackerBundle\Entity\Issue
    source:
      acl_resource: tracker.issue_view
      type: orm
      query:
        select:
          - i.id
          - i.code
          - i.summary
          - i.createdAt
          - i.updatedAt
          - type_enum.name as typeName
          - priority_enum.name as priorityName
          - status_enum.name as statusName
          - resolution_enum.name as resolutionName
        from:
          - { table: VitaliiTrackerBundle:Issue, alias: i }
        join:
          left:
            - { join: i.type, alias: type_enum }
            - { join: i.priority, alias: priority_enum }
            - { join: i.status, alias: status_enum }
            - { join: i.resolution, alias: resolution_enum }
    columns:
      code:
        label: Code
      summary:
        label: Summary
      typeName:
        label: Type
      priorityName:
        label: Priority
      statusName:
        label: Status
      resolutionName:
        label: Resolution
      createdAt:
        label: Created at
        frontend_type: date
      updatedAt:
        label: Updated at
        frontend_type: date
    properties:
      id: ~
      update_link:
        type: url
        route: tracker.issue_update
        params:
          - id
      view_link:
        type: url
        route: tracker.issue_view
        params:
          - id
      delete_link:
        type: url
        route: tracker.issue_delete
        params:
          - id
    sorters:
      columns:
        code:
          data_name: i.code
        typeName:
          data_name: type_enum.priority
        priorityName:
          data_name: priority_enum.priority
        statusName:
          data_name: status_enum.priority
        resolutionName:
          data_name: resolution_enum.priority
        createdAt:
          data_name: i.createdAt
        updatedAt:
          data_name: i.updatedAt
      default:
        updatedAt: DESC
    filters:
      columns:
        typeName:
          type: enum
          enum_code: issue_type
          data_name: typeName
        priorityName:
          type: enum
          enum_code: issue_priority
          data_name: priorityName
        statusName:
          type: enum
          enum_code: issue_status
          data_name: statusName
        resolutionName:
          type: enum
          enum_code: issue_resolution
          data_name: resolutionName
    actions:
      view:
        type:          navigate
        label:         View
        link:          view_link
        icon:          eye-open
        acl_resource:  tracker.issue_view
        rowAction:     true
      update:
        type:          navigate
        label:         Update
        link:          update_link
        icon:          edit
        acl_resource:  tracker.issue_update
      delete:
        type:          delete
        label:         Delete
        link:          delete_link
        icon:          trash
        acl_resource:  tracker.issue_delete
