parameters:
    vitalii_tracker.form.type.issue.class: Vitalii\Bundle\TrackerBundle\Form\Type\IssueType
    vitalii_tracker.form.event_listener.field_set.class: Vitalii\Bundle\TrackerBundle\Form\EventListener\FieldSetListener

services:
    vitalii_tracker.form.type.issue:
        class: '%vitalii_tracker.form.type.issue.class%'
        arguments:
            - '@tracker.issue.manager'
            - '@vitalii_tracker.form.event_listener.required_attributes'
        tags:
            - { name: form.type, alias: tracker_issue }

    vitalii_tracker.form.event_listener.required_attributes:
        class: '%vitalii_tracker.form.event_listener.field_set.class%'
