services:
  tracker.form.type.issue:
    class: Vitalii\Bundle\TrackerBundle\Form\Type\IssueType
    tags:
      - { name: form.type, alias: tracker_issue }
  tracker.form.type.issue_subtask:
    class: Vitalii\Bundle\TrackerBundle\Form\Type\IssueSubtaskType
    tags:
      - { name: form.type, alias: tracker_issue_subtask }
  tracker.form.type.issue_story:
    class: Vitalii\Bundle\TrackerBundle\Form\Type\IssueStoryType
    tags:
      - { name: form.type, alias: tracker_issue_story }
