parameters:
    vitalii_tracker_issue.importexport.strategy.issue.add_or_replace.class:  Vitalii\Bundle\TrackerBundle\ImportExport\Strategy\IssueAddOrReplaceStrategy
    vitalii_tracker_issue.importexport.helper.issue_import_helper.class:     Vitalii\Bundle\TrackerBundle\ImportExport\Strategy\IssueImportHelper

services:
    vitalii_tracker_issue.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    vitalii_tracker_issue.importexport.template_fixture.data_converter:
        parent: oro_importexport.data_converter.template_fixture.configurable

    vitalii_tracker_issue.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    vitalii_tracker_issue.importexport.helper.issue_import_helper:
        class: %vitalii_tracker_issue.importexport.helper.issue_import_helper.class%

    vitalii_tracker_issue.importexport.strategy.issue.add_or_replace:
        class: %vitalii_tracker_issue.importexport.strategy.issue.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setIssueImportHelper, ['@vitalii_tracker_issue.importexport.helper.issue_import_helper']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    vitalii_tracker_issue.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter,  ['@vitalii_tracker_issue.importexport.data_converter']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %vitalii_tracker.issue.entity.class%, alias: vitalii_tracker_issue }

    vitalii_tracker_issue.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter,  ['@vitalii_tracker_issue.importexport.template_fixture.data_converter']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %vitalii_tracker.issue.entity.class%, alias: vitalii_tracker_issue }

    vitalii_tracker_issue.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@vitalii_tracker_issue.importexport.data_converter.issue']]
            - [setStrategy, ['@vitalii_tracker_issue.importexport.strategy.issue.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %vitalii_tracker.issue.entity.class%, alias: vitalii_tracker_issue.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %vitalii_tracker.issue.entity.class%, alias: vitalii_tracker_issue.add_or_replace }
