placeholders:
    view_content_data_additional_information:
        items:
            vitalii_tracker_issues_assigned:
                order: 100
            vitalii_tracker_issues_reported:
                order: 200
    view_navButtons_before:
        items:
            vitalii_tracker_assign_issue:
                order: 100

items:
    vitalii_tracker_issues_assigned:
        template: VitaliiTrackerBundle:Issue:user_assigned_issues.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: "tracker.issue_view"
    vitalii_tracker_issues_reported:
        template: VitaliiTrackerBundle:Issue:user_reported_issues.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: "tracker.issue_view"
    vitalii_tracker_assign_issue:
        template: VitaliiTrackerBundle:Issue:assign_issue.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: "tracker.issue_create"
