services:
    security.access.issue_voter:
        class:      Vitalii\Bundle\TrackerBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
            - { name: security.voter }

    tracker.issue.manager:
        class:      Vitalii\Bundle\TrackerBundle\Manager\IssueManager
        arguments:  ["@doctrine", "@security.token_storage"]
