services:
    security.access.issue_voter:
        class:      Vitalii\Bundle\TrackerBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
            - { name: security.voter }

    tracker.issue.manager:
        class:      Vitalii\Bundle\TrackerBundle\Manager\IssueManager
        arguments:  ["@doctrine", "@security.token_storage"]

    tracker.mailer.processor:
        class: Vitalii\Bundle\TrackerBundle\Mailer\Processor
        arguments:
            - "@doctrine"
            - "@oro_config.global"
            - "@oro_email.email_renderer"
            - "@oro_email.email_holder_helper"
            - "@oro_email.direct_mailer"

    tracker.subtask_parent.validator:
        class: Vitalii\Bundle\TrackerBundle\Validator\Constraints\SubtaskParentValidator
        tags:
            - { name: validator.constraint_validator, alias: tracker_subtask_parent_validator }