Vitalii\Bundle\TrackerBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
        - Vitalii\Bundle\TrackerBundle\Validator\Constraints\SubtaskParent: ~
    properties:
        code:
            - NotBlank:     ~
            - Length:
                max:        255
        summary:
            - NotBlank:     ~
            - Length:
                max:        255
