workflows:
    issue_status:
        label: 'Issue Workflow'
        entity: Vitalii\Bundle\TrackerBundle\Entity\Issue
        entity_attribute: issue
        start_step: open
        steps_display_ordered: true

        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                   - stop_progress
                   - resolve
                   - close
            closed:
                label: 'Closed'
                order: 30
                allowed_transitions:
                   - reopen
            resolved:
                label: 'Resolved'
                order: 40
                allowed_transitions:
                   - close
                   - reopen
            reopened:
                label: 'Reopened'
                order: 50
                allowed_transitions:
                   - start_progress

        attributes:
            resolution:
                property_path: issue.resolution

        transitions:
            start_progress:
                label: 'Start progress'
                step_to: in_progress
                transition_definition: start_progress_definition
            resolve:
                label: 'Resolve'
                step_to: resolved
                transition_definition: resolve_definition
                form_options:
                    attribute_fields:
                        resolution:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
            close:
                label: 'Close'
                step_to: closed
                transition_definition: close_definition
            reopen:
                label: 'Reopen'
                step_to: reopened
                transition_definition: reopen_definition
            stop_progress:
                label: 'Stop progress'
                step_to: open
                transition_definition: stop_progress_definition

        transition_definitions:
            start_progress_definition: []
            resolve_definition: []
            close_definition: []
            reopen_definition:
                post_actions:
                    - @call_method:
                        object: $issue
                        method: setResolution
                        method_parameters:
                            [null]
            stop_progress_definition: []
