operations:
    add_subtask_action:
        label: "Add Subtask"
        entities:
            - Vitalii\Bundle\TrackerBundle\Entity\Issue
        routes:
            - "tracker.issue_view"
        preconditions:
            @equal: [$type.id, "story"]
        actions:
            - @redirect:
                route: "tracker.issue_subtask"
                route_parameters:
                    issue_code: $code
