oro_chart:
    issue_line_chart:
        label: oro.chart.bar_chart.label
        data_schema:
            label:
                name: label
                label: Step
                required: true
                default_type: string
                field_name: step
            value:
                name: value
                label: Count
                required: true
                default_type: number
                field_name: total
        default_settings:
            connect_dots_with_line: true
            available_in_reports: false
            chartColors: ['#6598DA', '#ECC87E', '#A4A2F6', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
            groupingOption: name
        template: OroChartBundle:Chart:bar.html.twig
